//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seckinkirtasiye.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seckinkirtasiyeEntities : DbContext
    {
        public seckinkirtasiyeEntities()
            : base("name=seckinkirtasiyeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AboutUs> tbl_AboutUs { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_Gallery> tbl_Gallery { get; set; }
        public virtual DbSet<tbl_Marka> tbl_Marka { get; set; }
        public virtual DbSet<tbl_Services> tbl_Services { get; set; }
        public virtual DbSet<tbl_slider> tbl_slider { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
