//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seckinkirtasiye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Services
    {
        public int Service_ID { get; set; }
        public string Service_Name { get; set; }
        public string Service_Text { get; set; }
        public string Service_Image { get; set; }
    }
}
