//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seckinkirtasiye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_slider
    {
        public int Slider_image_ID { get; set; }
        public string Slider_image { get; set; }
        public string Slider_image_title { get; set; }
        public string Slider_image_text { get; set; }
    }
}
