//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seckinkirtasiye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int Contact_ID { get; set; }
        public string Google { get; set; }
        public string Adress { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Cep_Tel { get; set; }
        public string Mail { get; set; }
    }
}
